const express = require('express')
const homeRoutes = require('./Routes/Home')
const orderRouter = require('./Routes/Orders')
const ProjectRoutes = require('./Routes/Projects')
const catRouter = require('./Routes/Category')
const MembersRouter = require('./Routes/Membership')
const cookieParser = require('cookie-parser')
const device = require('express-device')
const {getUser, checkAuth} = require('./Middlewares/AuthMiddleware')
const connDb = require('./Database')
 const app = express()
 app.use(device.capture());
 app.listen(8080,()=>{
   console.log('Server running on http://localhost:8080/')
   connDb()
 })
 app.set('trust proxy', true)
 app.use(cookieParser())
 app.use(express.static('Resources'))
 app.use(express.json())
app.use(express.urlencoded({extended:true}))
 app.set('view engine','ejs')
 app.set('views','Views') 
 app.get('*',getUser)
 app.use(homeRoutes)
 app.use(ProjectRoutes)
 app.use(orderRouter)
 app.use(catRouter)
 app.use(MembersRouter)
 app.use((req,res)=>{
    res.render('pages/Error.ejs',{title:'Error!!!Page Not Found'})
 })