const express = require('express')
const homeRoutes = require('./Routes/Home')
const cookieParser = require('cookie-parser')
const {getUser} = require('./Middlewares/AuthMiddleware')
const connDb = require('./Database')
 const app = express()

 app.listen(8080)
 connDb()
 app.use(cookieParser())
 app.use(express.static('Resources'))
 app.use(express.json())
app.use(express.urlencoded({extended:true}))
 app.set('view engine','ejs')
 app.set('views','Views') 
 app.get('*',getUser)
 app.use(homeRoutes)
 app.use((req,res)=>{
    res.render('pages/Error.ejs',{title:'Error!!!Page Not Found'})
 })