const express = require('express')
const {checkAuth} = require('../Middlewares/AuthMiddleware')
const {Index,
    About,Services,Pricing,Portfolio,FAQ,Blog,Contact,Subscribe,Register,Login,Reset,RegisterUser,LoginUser,Dashboard,Logout} = require('../Controller/HomeViewController')
const homeRoute = express.Router()

homeRoute.get("/",Index)
.get('/About',About)
.get('/Services',Services)
.get('/Pricing',Pricing)
.get('/Portfolio',Portfolio)
.get('/Blog',Blog)
.get('/FAQ',FAQ)
.get('/Contact',Contact)
.get('/Subscribe',checkAuth,Subscribe)
.get('/Register',Register)
.get('/Login',Login)
.get('/Reset',Reset)
.get('/Dashboard',checkAuth,Dashboard)
.post('/Register',RegisterUser)
.post('/Login',LoginUser)
.get('/Logout',Logout)
module.exports = homeRoute